In [ ]:
# For GPU users
!pip install tensorflow[and-cuda]
# For CPU users
!pip install tensorflow


Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable


In [ ]:
!pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable


In [3]:
!pip3 install -U scikit-learn

Defaulting to user installation because normal site-packages is not writeable


In [4]:
!pip install mediapipe

Defaulting to user installation because normal site-packages is not writeable


In [1]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp

2023-11-14 08:04:40.031950: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-14 08:04:40.079878: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-14 08:04:40.494980: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-14 08:04:40.498181: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-14 08:04:43.483589: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [2]:
mp_holistic  = mp.solutions.holistic #holistic model
mp_drawing = mp.solutions.drawing_utils #utilidades de dibujo

In [3]:
def mediapipe_detection(image,model):
    image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB) # convierte de BGR a RGB
    image.flags.writeable = False  #La imagen no es writeable
    results = model.process(image)  #image es el frame del open cv, hace la prediccion
    image.flags.writeable = True     #la imagen es writable 
    image = cv2.cvtColor(image,cv2.COLOR_RGB2BGR) #convierte de RGB a BGR
    return image,results 


In [4]:
def mediapipe_detection(image, model):
    # Convert from BGR to RGB
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    
    # Make a copy of the image to avoid modifying the original image
    input_image = np.copy(image_rgb)
    
    # Make the input image non-writable before processing
    input_image.flags.writeable = False
    
    # Perform detection
    results = model.process(input_image)
    
    # Make the input image writable again
    input_image.flags.writeable = True
    
    # Convert the image back from RGB to BGR
    image = cv2.cvtColor(input_image, cv2.COLOR_RGB2BGR)
    
    return image, results


In [5]:
def draw_landmarks(image,results): #dibujar las marcas en la imagen
    mp_drawing.draw_landmarks(image,results.face_landmarks,mp_holistic.FACEMESH_TESSELATION) #dibuja las conecciones de la cara
    mp_drawing.draw_landmarks(image,results.pose_landmarks,mp_holistic.POSE_CONNECTIONS) #Dibuja las pose conecciones
    mp_drawing.draw_landmarks(image,results.left_hand_landmarks,mp_holistic.HAND_CONNECTIONS) #dibuja las conecciones de la mano izquierda
    mp_drawing.draw_landmarks(image,results.right_hand_landmarks,mp_holistic.HAND_CONNECTIONS) #dibuja las conecciones de la mano derecha 

    

In [6]:
def draw_styled_landmarks(image,results): #dibuja los landmarks refinados 
    mp_drawing.draw_landmarks(image,results.face_landmarks,mp_holistic.FACEMESH_TESSELATION,mp_drawing.DrawingSpec(color=(80,110,10),thickness=1,circle_radius=1),mp_drawing.DrawingSpec(color=(80,256,121),thickness=1,circle_radius=1)) #dibuja las conecciones de la cara
    mp_drawing.draw_landmarks(image,results.pose_landmarks,mp_holistic.POSE_CONNECTIONS,mp_drawing.DrawingSpec(color=(80,22,10),thickness=2,circle_radius=4),mp_drawing.DrawingSpec(color=(80,44,121),thickness=2,circle_radius=2)) #Dibuja las pose conecciones
    mp_drawing.draw_landmarks(image,results.left_hand_landmarks,mp_holistic.HAND_CONNECTIONS,mp_drawing.DrawingSpec(color=(121,22,76),thickness=2,circle_radius=4),mp_drawing.DrawingSpec(color=(121,44,250),thickness=2,circle_radius=2)) #dibuja las conecciones de la mano izquierda
    mp_drawing.draw_landmarks(image,results.right_hand_landmarks,mp_holistic.HAND_CONNECTIONS,mp_drawing.DrawingSpec(color=(245,117,66),thickness=2,circle_radius=4),mp_drawing.DrawingSpec(color=(245,66,230),thickness=2,circle_radius=2)) #dibuja las conecciones de la mano derecha 


In [7]:
#abre la webcam y va entre los frames
cap = cv2.VideoCapture(0)
#setteamos el modelo de mediapipe
with mp_holistic.Holistic(min_detection_confidence = 0.5, min_tracking_confidence = 0.5) as holistic:
  while cap.isOpened():
    #lee el feed
    ret,frame = cap.read()

    #hace la deteccion
    image, results = mediapipe_detection(frame,holistic)
    print(results)
    #dibuja  los landmarks
    draw_styled_landmarks(image,results)
    #Lo muestra en la pantalla
    cv2.imshow('OpenCV Feed',image)

    #Rompe el loop si se apreta q
    if cv2.waitKey(10) & 0xFF == ord('q'):
      break
  cap.release()
  cv2.destroyAllWindows()

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.


<class 'mediapipe.python.solution_base.SolutionOutputs'>


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/mache12/.local/lib/python3.10/site-packages/cv2/qt/plugins"


<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>


In [8]:
pose = [] #array para gaursar los landmarks
for res in results.pose_landmarks.landmark:
    test = np.array([res.x,res.y,res.z,res.visibility])
    pose.append(test)

In [9]:
pose = np.array([[res.x,res.y,res.z,res.visibility]for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)#todos los landmarks en un solo array grande
face = np.array([[res.x,res.y,res.z]for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)#todos los landmarks en un solo array grande
lh = np.array([[res.x,res.y,res.z]for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)#todos los landmarks en un solo array grande
rh = np.array([[res.x,res.y,res.z]for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)#todos los landmarks en un solo array grande

In [10]:

def extract_keypoints(results):
    pose = np.array([[res.x,res.y,res.z,res.visibility]for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)#todos los landmarks en un solo array grande
    face = np.array([[res.x,res.y,res.z]for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)#todos los landmarks en un solo array grande
    lh = np.array([[res.x,res.y,res.z]for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)#todos los landmarks en un solo array grande
    rh = np.array([[res.x,res.y,res.z]for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)#todos los landmarks en un solo array grande
    return np.concatenate([pose,face,lh,rh])
    

In [11]:
result_test = extract_keypoints(results)

In [12]:
result_test

array([ 0.48899198,  0.6679185 , -1.65229762, ...,  0.37151602,
        0.85883176, -0.03320272])

In [17]:
np.save('0',result_test)

In [18]:
np.load('0.npy')

array([ 0.43697825,  0.51879418, -0.86420983, ...,  0.        ,
        0.        ,  0.        ])

In [13]:
extract_keypoints(results).shape

(1662,)

In [15]:
#path para la data exportada
DATA_PATH = os.path.join('MP_Data') # variable que guarda 

#Aciones detectadas
actions = np.array(['hello','thanks','iloveyou'])
no_sequences = 30 #Cantidad de videos que se recolectaran por accion
sequence_length = 30 #30 es la cantidad de frames de data que va a utilizar 
#lo que se hara para la info es recolectar 30 videos de 30 frames cada un por accion (son 3 acciones) por la cantidad de keypoints que se tienen que son 1662 (entre todas las  variables)

In [16]:
for action in actions: 
    for sequence in range(no_sequences):
        try: 
            os.makedirs(os.path.join(DATA_PATH,action,str(sequence)))
        except:
            pass

In [22]:
cap = cv2.VideoCapture(0)
#setteamos el modelo de mediapipe
with mp_holistic.Holistic(min_detection_confidence = 0.5, min_tracking_confidence = 0.5) as holistic:
    for action in actions:
        for sequence in range(no_sequences):
            for frame_num in range(sequence_length):
    #lee el feed
                ret,frame = cap.read()

    #hace la deteccion
                image, results = mediapipe_detection(frame,holistic)
                #print(results)
            #dibuja  los landmarks
                draw_styled_landmarks(image,results)
            
                if frame_num == 0 :
                    cv2.putText(image,'Sarting Collection',(120,200),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2,cv2.LINE_AA)# IMprime Starting Collection
                    cv2.putText(image,'Colelecting Frames for {} Video Number {}'.format(action,sequence),(15,12),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),1,cv2.LINE_AA)
                    cv2.imshow('OpenCV Feed',image)
                    cv2.waitKey(1500)

            
                else :
                    cv2.putText(image,'Colelecting Frames for {} Video Number {}'.format(action,sequence),(15,12),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),1,cv2.LINE_AA)
                    cv2.imshow('OpenCV Feed',image)

                #Exportamos los Keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH,action,str(sequence),str(frame_num))
                np.save(npy_path,keypoints)

                #Rompe el loop si se apreta q
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
    cap.release()
    cv2.destroyAllWindows()

In [17]:
cap.release()
cv2.destroyAllWindows()

In [38]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [39]:
label_map = {label:num for num, label in enumerate(actions)} #esto loopea entre cada una de las palabras

In [40]:
label_map #se estructura en un array grande por accion, se termina creando 90 arrays con 30 fraames en cada array con 1662 valores que representan los keypoints

{'hello': 0, 'thanks': 1, 'iloveyou': 2}

In [41]:
sequences, labels = [],[] # sequences representa la dara y labels representa los label
for action in actions: # se loopea entre las acciones y las sequencias
    for sequence in range(no_sequences):
        window = [] #windows representa todas las ventanas de video
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH,action,str(sequence),"{}.npy".format(frame_num))) # se cargan los diferentes frames desde las carpetas  
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [42]:
np.array(sequences).shape

(90, 30, 1662)

In [43]:
np.array(labels).shape

(90,)

In [44]:
X = np.array(sequences)

In [45]:
X.shape

(90, 30, 1662)

In [46]:
y = to_categorical(labels).astype(int)

In [47]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.05)

In [48]:
y_test.shape

(5, 3)

In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [50]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir = log_dir)

In [52]:

model = Sequential() # Se rean layers para entrenar los modelos 
model.add(LSTM(64,return_sequences = True, activation='relu',input_shape = (30,1662)))
model.add(LSTM(128,return_sequences = True, activation='relu'))
model.add(LSTM(64,return_sequences = False, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0],activation = 'softmax')) #softmas te da un conjunto de probabilidades que sumadas te suman 1  

In [53]:
res = [.7,0.2,0.1]

In [54]:
actions[np.argmax(res)]

'hello'

In [56]:
model.compile(optimizer = 'Adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])

In [57]:

model.fit(X_train,y_train, epochs = 2000, callbacks = [tb_callback])

Epoch 1/2000
3/3 [==============================] - 5s 78ms/step - loss: 1.1442 - categorical_accuracy: 0.3412
Epoch 2/2000
3/3 [==============================] - 0s 73ms/step - loss: 2.1150 - categorical_accuracy: 0.3882
Epoch 3/2000
3/3 [==============================] - 0s 70ms/step - loss: 1.7784 - categorical_accuracy: 0.4353
Epoch 4/2000
3/3 [==============================] - 0s 68ms/step - loss: 2.0934 - categorical_accuracy: 0.3647
Epoch 5/2000
3/3 [==============================] - 0s 73ms/step - loss: 1.1049 - categorical_accuracy: 0.3765
Epoch 6/2000
3/3 [==============================] - 0s 67ms/step - loss: 1.1051 - categorical_accuracy: 0.3294
Epoch 7/2000
3/3 [==============================] - 0s 76ms/step - loss: 1.1007 - categorical_accuracy: 0.3294
Epoch 8/2000
3/3 [==============================] - 0s 81ms/step - loss: 1.0792 - categorical_accuracy: 0.4000
Epoch 9/2000
3/3 [==============================] - 0s 72ms/step - loss: 1.0185 - categorical_accuracy: 0.5647
E

In [58]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 30, 64)            442112    
                                                                 
 lstm_4 (LSTM)               (None, 30, 128)           98816     
                                                                 
 lstm_5 (LSTM)               (None, 64)                49408     
                                                                 
 dense_3 (Dense)             (None, 64)                4160      
                                                                 
 dense_4 (Dense)             (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 3)                 99        
                                                                 
Total params: 596675 (2.28 MB)
Trainable params: 59667

In [59]:
res = model.predict(X_test)

1/1 [==============================] - 0s 460ms/step


In [64]:
actions[np.argmax(res[4])]

'hello'

In [65]:
actions[np.argmax(y_test[4])]

'hello'

In [66]:
model.save('action.h5')

/home/mache12/.local/lib/python3.10/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [67]:
model.load_weights('action.h5')

In [68]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [69]:
yhat = model.predict(X_test)

1/1 [==============================] - 0s 37ms/step


In [70]:
ytrue = np.argmax(y_test, axis = 1).tolist()
yhat =  np.argmax(yhat,axis = 1).tolist()

In [71]:
multilabel_confusion_matrix(ytrue,yhat)

array([[[2, 1],
        [0, 2]],

       [[4, 0],
        [1, 0]],

       [[2, 1],
        [1, 1]]])

In [72]:
accuracy_score(ytrue,yhat)

0.6

*Real time Testing*

In [107]:
colors = [(245,117,16),(117,245,16),(16,117,245),(16,117,245),(16,117,245)]
def prob_viz(res,actions,imput_frame,colors):
    output_frame = imput_frame.copy()
    for num,prob in enumerate(res):
        cv2.rectangle(output_frame,(0,60+num*40),(prob,90+num*40), colors[num],-1)
        cv2.putText(output_frame,actions[num],(0,85+num*40), cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2,cv2.LINE_AA)
   
    return output_frame

In [109]:
plt.figure(figsize=(18,18))
plt.imshow(prob_viz(res,actions,image,colors))

error: OpenCV(4.8.1) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - Can't parse 'pt2'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt2'. Sequence item with index 0 has a wrong type
>  - Can't parse 'rec'. Expected sequence length 4, got 2
>  - Can't parse 'rec'. Expected sequence length 4, got 2


<Figure size 1296x1296 with 0 Axes>

In [88]:
sequence.reverse()

AttributeError: 'int' object has no attribute 'reverse'

In [89]:
len(sequence)

TypeError: object of type 'int' has no len()

In [90]:
sequence.append('def')

AttributeError: 'int' object has no attribute 'append'

In [91]:
sequence.reverse()

AttributeError: 'int' object has no attribute 'reverse'

In [ ]:
sequence[-30:]

[array([ 0.58613384,  0.73865139, -0.8673951 , ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.58584559,  0.72018433, -0.82997513, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.58735293,  0.73006111, -0.85942733, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.59121954,  0.82920718, -0.84646225, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.62477839,  0.93532568, -0.85378599, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.69186652,  0.97556645, -0.80356312, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.70692319,  0.96941251, -0.74277455, ...,  0.34524983,
         0.9708609 , -0.06021295]),
 array([ 0.70449054,  0.92674023, -0.76636249, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.583112  ,  0.77072316, -0.83221102, ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.5622431 ,  0.67805398, -0.99790621, ...,  0.        ,
         0.        ,  0.  

In [97]:
#Variables de deteccion

sequence = []
sentence = []
predictions = []
threshold = 0.5


#abre la webcam y va entre los frames
cap = cv2.VideoCapture(0)
#setteamos el modelo de mediapipe
with mp_holistic.Holistic(min_detection_confidence = 0.5, min_tracking_confidence = 0.5) as holistic:
  while cap.isOpened():
    #lee el feed
    ret,frame = cap.read()

    #hace la deteccion
    image, results = mediapipe_detection(frame,holistic)
    print(results)
    #dibuja  los landmarks
    draw_styled_landmarks(image,results)
    keypoints = extract_keypoints(results)
    sequence.append(keypoints)
    #[-30:] son los ultimos 30 frames/ 30 set de keypoints
    sequence = sequence[-30:]
    
    #si la longitud de la sequencia tiene una longitud de 30 frames, recien ahi se hace la prediccion
    if len(sequence) == 30:
        res = model.predict(np.expand_dims(sequence,axis = 0))[0]
        print(actions[np.argmax(res)])
        predictions.append(np.argmax(res))
        
        
       #viz Logic 
        if np.unique(predictions[-10:])[0] == np.argmax(res):
          if res[np.argmax(res)] > threshold:
            if len(sentence) > 0:
              if actions[np.argmax(res)] != sentence[-1]:
                sentence.append(actions[np.argmax(res)])
              else:
                sentence.append(actions[np.argmax(res)])
      
          if len(sentence) > 5:
            sentence = sentence[-5:]
    
    #Visualizar probabilidades
    image = prob_viz(res,actions,image, colors)
    
    cv2.rectangle(image,(0,0),(640,40),(245,117,16),-1)
    cv2.putText(image,' '.join(sentence),(3,30),cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2,cv2.LINE_AA)
          
    
    #Lo muestra en la pantalla
    cv2.imshow('OpenCV Feed',image)

    #Rompe el loop si se apreta q
    if cv2.waitKey(10) & 0xFF == ord('q'):
      break
  cap.release()
  cv2.destroyAllWindows()

[ WARN:0@2268.557] global cap_v4l.cpp:982 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@2268.558] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range


In [ ]:
cap.release()
cv2.destroyAllwindows()

AttributeError: module 'cv2' has no attribute 'destroyAllwindows'

In [ ]:
res[np.argmax(res)] >threshold

True

In [ ]:
(num_sequences,30,1662)

NameError: name 'num_sequences' is not defined

In [ ]:
model.predict(np.expand_dims(X_test[0],axis = 0 ))

1/1 [==============================] - 0s 45ms/step


array([[9.4910263e-08, 1.5349721e-08, 9.9999988e-01]], dtype=float32)